x-common: &common-setup
  build: .
  image: ros2_px4_gazebo:common # ros2_px4:common  # fabook/mik:common
  network_mode: host
  privileged: true
  volumes: 
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/root/ros2_px4_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw

  environment:
    - "DISPLAY"
    - "QT_X11_NO_MITSHM=1"
  ports:
    - "9090:9090"
  entrypoint: >
    bash -c "
    source /opt/ros/humble/setup.bash && /bin/bash
    "

services:
  terminal:
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    working_dir: /root/ros2_px4_ws
    command: []
    restart: always
